### ISSUE TITLE
Provide esm build

### ISSUE THREAD

**Issue by stefanjudis** [alex-page/a11ycolor#25]
Hey Alex,

thank you for this package. I just did a quick search on npm and this package is exactly what I was looking for. I want to use it in an **ES module environment**. Do you have plans to make this module also available with JavaScript modules? Currently, it's only published for node using CommonJS. :) 

That would be fantastic. :)

**Comment by alex-page** [comment]
Hey @stefanjudis sorry for the super late reply. I'll see what I can do. I totally missed this issue.

**Comment by alex-page** [comment]
@stefanjudis I looked into this I am having some trouble with the color dependency and building this into an ES module environment. Have you ever experienced this before? I am using https://github.com/developit/microbundle.

**Comment by stefanjudis** [comment]
Unfortunately, I don't have time to look into this. :/ And I also don't remember anymore for what I needed your package. 🙈 Feel free to close this issue.

**Comment by alex-page** [comment]
Ok thanks for reaching out and creating an issue. I appreciate it!
